version: Wesnoth-VS2015-{branch}-{build}
clone_folder: C:\projects\wesnoth
image: Visual Studio 2015
configuration:
 - Release
 - Debug
platform: win32
skip_branch_with_pr: true
shallow_clone: true
before_build:
  - cd ..
  - ps: wget https://github.com/aquileia/external/archive/VC14.zip -O VC14.zip
  - 7z x VC14.ZIP
  - ren external-VC14 external
  - cd wesnoth
  - mkdir projectfiles\VC14
  - xcopy /E /I /H /Y projectfiles\VC12 projectfiles\VC14
  - cd projectfiles\VC14
  - "\"c:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\devenv.exe\" wesnoth.sln /upgrade"
  - cd ..\..
  - set PATH=C:\projects\external\dll;%PATH%
build_script:
  - msbuild projectfiles\VC14\wesnoth.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

on_failure:
  - "python utils\\appveyor\\irc-notify.py wesnoth-dev {bold}{project_name} - {configuration_name} {color_green}{author}{plain} {bold}{short_commit}: {plain}{message} {color_red}Failed,{bold}Details: {plain}{build_url}"
