version: Wesnoth-VS2015-{branch}-{build}
clone_folder: C:\projects\wesnoth
image: Visual Studio 2015
configuration:
 - Release
 - Debug
platform: win32
skip_branch_with_pr: true
shallow_clone: true
matrix:
  fast_finish: true # Stop after a build failure
before_build:
  - cd ..
  - ps: wget https://github.com/aquileia/external/archive/VC14.zip -O VC14.zip
  - 7z x VC14.ZIP
  - ren external-VC14 external
  - cd wesnoth
  - set PATH=C:\projects\external\dll;%PATH%

notifications:
  - provider: Webhook
    url: http://ai0867.net:6661/wesnoth
    headers:
      User-Agent: WesnothAppveyor/1.0
      Version: vs2015
      Num-Versions: 3
      Authorization: TODO
    on_build_success: true
    on_build_failure: true
