version: Wesnoth-VS2017-{branch}-{build}
clone_folder: C:\projects\wesnoth
image: Visual Studio 2017
configuration:
 - Release
 - Debug
platform: win32
skip_branch_with_pr: true
shallow_clone: true
matrix:
  fast_finish: true # Stop after a build failure
before_build:
  - cd ..
  - ps: wget https://github.com/aquileia/external/archive/VC15.zip -O VC15.zip
  - 7z x VC15.ZIP
  - ren external-VC15 external
  - cd wesnoth
  - set PATH=C:\projects\external\dll;%PATH%
build_script:
  - msbuild projectfiles\VC12\wesnoth.sln /property:PlatformToolset=v141 /m /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

artifacts:
  - path: wesnoth.exe
  - path: wesnothd.exe

notifications:
  - provider: Webhook
    url: http://ai0867.net:6661/wesnoth
    headers:
      User-Agent: WesnothAppveyor/1.0
      Version: vs2017
      Num-Versions: 3
      Authorization: TODO
    on_build_success: true
    on_build_failure: true
